### ISSUE TITLE
psc-bundle is unable to parse module when `purescript-spec` is installed

### ISSUE THREAD

**Issue by cxfreeio** [owickstrom/purescript-spec#12]
`psc-bundle` (and `pulp build` with the `--to` flag) gives me the error `The module could not be parsed.` whenever `Test.Spec.*` modules have been built to the `output` directory. When I delete those directories, I am able to bundle. Any idea what's causing this?

**Comment by owickstrom** [comment]
Hmm, not able to recreate this. Could you provide a minimal project and list the commands you're running? Thanks!

**Comment by cxfreeio** [comment]
Sure, here's output from my shell; let me know if you need any more info:

``` shell
==> mkdir example

==> cd example

==> pulp -v
4.3.0

==> psc --version
0.7.0.0

==> pulp init
[installations elided]

==> pulp build --to out.js
* Building project in /Users/am/w/example2
* Build successful.
* Bundling Javascript...
* Bundled.

==> node out.js
Hello sailor!

==> rm -f out.js

==> pulp dep i purescript-spec
[installations elided]

==> pulp build --to out.js
* Building project in /Users/am/w/example2
* Build successful.
* Bundling Javascript...
The module could not be parsed.

* ERROR: Subcommand terminated with error code 1

==> psc-bundle output/**/*.js --module Main --main Main > out.js
The module could not be parsed.

==>
```

**Comment by owickstrom** [comment]
Thank you!

It seems that the escape sequence at https://github.com/owickstrom/purescript-spec/blob/master/src/Test/Spec/Console.purs#L22 gets interpreted during the PS -> JS compilation. The module in `output/` contains the unescaped character which causes the bundle to fail. I'll try to move the string literal with the escape to a foreign function and see if that works.

Related issues: https://github.com/purescript/purescript/issues/1265 and https://github.com/purescript/purescript/pull/1266

**Comment by owickstrom** [comment]
I did a workaround for this and released a new version `0.7.1` that should work. Thanks for the feedback!

**Comment by cxfreeio** [comment]
The new version works - thank you!

**Comment by michaelficarra** [comment]
FYI purescript/purescript#1265 is fixed now!
