### ISSUE TITLE
"only" modifier

### ISSUE THREAD

**Issue by felixSchl** [owickstrom/purescript-spec#16]
Is there something like mocha's `only` modifier (i.e. `it.only`) to only run a certain test?

**Comment by owickstrom** [comment]
Not right now, but that would be nice. How about a flag or environment variable on the command line, e.g. `SPECS='Foo.*' pulp test`?

Thanks!

**Comment by felixSchl** [comment]
That would be cool as well, but I can see more use if I could do it from code. The reason being that if I have `pulp -w test` running, I change this setting mid-way through.

**Comment by felixSchl** [comment]
I just had a look through the code, I think adding this would be hard because each it block immediately executes if I am not mistaken. I think this whole project would be a perfect match for the [Free monad](https://github.com/purescript/purescript-free)? What do you think? I would be keen to do some work for the learning experience.

**Comment by owickstrom** [comment]
Yes, I agree, getting that lazy execution of tests is something that I've wanted to do. The current design makes it quirky to implement the Mocha reporter and support async, I think that might be simpler with a Free monad design as well.

If you'd like to have a stab at it that would be great!

**Comment by owickstrom** [comment]
@felixSchl Did you try anything out with the Free monad?

**Comment by felixSchl** [comment]
Nothing worth mentioning. I still think it's something very desirable to have, I just didn't have the time to invest into it. Not sure if the Free monad would work, how would you capture the arbitrary user code that runs as part of `it` in a data type?

**Comment by owickstrom** [comment]
I guess the ADT would need to keep that Aff value and run it on interpretation. Would be cool to investigate this track. I have so little time right now, though. 😞

**Comment by felixSchl** [comment]
Alternatively we could put it behind a function: `Unit -> Aff _ _`

**Comment by owickstrom** [comment]
Sure, that may be the best way.

If we could sync a time then maybe we could hack on this over Skype, hangouts or whatever?

**Comment by owickstrom** [comment]
At least to have some starting point.

**Comment by felixSchl** [comment]
yeah hangouts would be best, I'm not big on skype. It's just this email address.

**Comment by owickstrom** [comment]
I'm closing this as we're not currently progressing. If we want to try the Free monad approach later on I think that's a bigger redesign. Thanks!
