### ISSUE TITLE
Reporter reexports

### ISSUE THREAD

**Issue by felixSchl** [owickstrom/purescript-spec#37]
Version 0.11 introduced convenient re-exports in `Test.Spec.Reporter` that have consequently been removed (accidentally?). Personally, I would welcome these convenience exports as it means I can easily import bundled reporters downstream, i.e. `import Test.Spec.Reporter (consoleReporter)`. I apologize for not letting you know about adding these changes when crafting #32, I simply forgot amidst the many other changes.

**Comment by owickstrom** [comment]
My bad, let's re-add them! Thanks. 👍

**Comment by owickstrom** [comment]
Closed by d685184.
