### ISSUE TITLE
Export run' function

### ISSUE THREAD

**Issue by starper** [owickstrom/purescript-spec#39]
Sorry, but you forgot to actually export `run'` function. As you can see, there is only `run` function, that is exported:
``` purescript
module Test.Spec.Runner
       ( RunnerEffects
       , run
       , runSpec
       , runSpec'
       , defaultConfig
       , timeout
       , Config
       , TestEvents
       , Reporter
) where
```

**Comment by owickstrom** [comment]
Oh, stupid of me. I'm the one that should say sorry. :)

**Comment by owickstrom** [comment]
0.12.3 released: https://pursuit.purescript.org/packages/purescript-spec/0.12.3

**Comment by starper** [comment]
Thanks for your work :)
