### ISSUE TITLE
Time for v1.0.0?

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/purescript-spec#46]
I feel the API of this package is solid now, and not breaking often. There are some more features we'd like to have, but I think they can be added without breaking compatibility with existing users' code. Thus, I think we should go for version 1.0.0 to signal the stability.

@felixSchl thoughts?

**Comment by felixSchl** [comment]
I think you are right. If we go for an approach where `it` will take another parameter for context variables, I think we can introduce it with a similarly named function and then deprecate if we feel like that's the way to go. Would we jump to 4.0.0 to signal latest purescript compat?

**Comment by owickstrom** [comment]
Yes, and perhaps under the same name `it`. If the user has no context argument, the test body type could probably be the same as before. Anyway, we should go ahead and bump the version, IMO.

I see some packages at 3.0.0 with 0.11.x support, so there might be some different takes on that? If there's no consensus on a specific version for this compiler release, I think 1.0.0 would work for this package. Sounds OK?

**Comment by felixSchl** [comment]
Sorry for the late reply, I am easy on this and 1.0.0 seems fine to me and I also think it's time to signal stability unless you think we should get #50 out of the way first? Seems like a minor enough issue in the grand scheme of things to fix in a successive patch version.

**Comment by owickstrom** [comment]
Yes, I agree, we can do that later. I'll bump versions then.
