### ISSUE TITLE
slow :: Int is not used in Dot reporter

### ISSUE THREAD

**Issue by safareli** [owickstrom/purescript-spec#47]
DotReporterConfig contains `slow` prop which is not used in [`dotReporter`](https://github.com/owickstrom/purescript-spec/blob/master/src/Test/Spec/Reporter/Dot.purs#L14-L19)

**Comment by owickstrom** [comment]
Thanks for reporting! It was moved to the runner (https://github.com/owickstrom/purescript-spec/blob/master/src/Test/Spec/Runner.purs#L49), and should be removed. I'll fix it.

**Comment by owickstrom** [comment]
Removed now, and released together with your PR in [0.14.0](https://pursuit.purescript.org/packages/purescript-spec/0.14.0).

**Comment by safareli** [comment]
🚀
