### ISSUE TITLE
Add to psc-package set?

### ISSUE THREAD

**Issue by mostalive** [owickstrom/purescript-spec#53]
I've created a pull request on package-sets https://github.com/purescript/package-sets/pulls , after adding pipes and its' dependency mmorph.

I'd be happy to contribute my psc-package.json as well. psc-package only runs 'build' at the moment, there is preliminary support for using it with pulp as well. I haven't figured out how best to run tests with it, I thought at least getting 'spec' to compile would be a good start.

(added because I've been bitten by transitive dependency hell with bower, the last time bower won and this seemed like a worthwile thing to try. Also frees purescript-spec from worrying about synchronizing version numbers with other packages or not.).

**Comment by owickstrom** [comment]
Hey, sorry to kept this issue lying around so long. I'm not using psc-package so I'm not sure how it would work and how much work it would be to keep them in sync. Sadly, I'm not using PureScript at all at the moment and my time is stretched thin for OSS work. If we add a psc-package.json, do you think it could become a problem (e.g. becoming outdated)?

**Comment by mostalive** [comment]
Hey, Sorry here too. There are two ways in which it can become outdated:
- refers to an old version of the package set
- misses a dependency that gets added

Both should be less work than updating bower.json (which unfortunately also still appears to be necessary) with all it's version bounds (my workflow there is run `npm-check-updates` and hope for the best)

In a way, having a psc-package.json is somewhat duplicated, since it is in the package set, where the dependencies are also listed (and the version of the package set is inherent). I think it just makes it that bit easier to check out the project from source and work on it.

(In the meantime bower gets more and more deprecated. Installing it now gives a warning to install yarn and convert the bower file to yarn, but on the yarn end support for bower appears to have been dropped, I can dig up the links if desired).

**Comment by owickstrom** [comment]
All right. Yeah, I think you can add it then. 👍

**Comment by felixmulder** [comment]
This could be closed now I think since psc-package has this :tada:

**Comment by mostalive** [comment]
I was thinking the same thing, but didn't have time to check :tada:
