### ISSUE TITLE
Node.Process

### ISSUE THREAD

**Issue by Risto-Stevcev** [owickstrom/purescript-spec#55]
The Node.Process dependency is placing a hard dependency where you have to run the tests on nodejs. The issue with that is that you can't use something like phantomjs to run tests and test libraries that interact with the DOM.

How do you feel about going back to defining a custom PROCESS effect?

**Comment by owickstrom** [comment]
Yeah, that is unfortunate. We could basically revert 9ce8ebf76f4c2a1a7802b93fa4456831db174ff8. Something you'd like to send a PR for?

**Comment by Risto-Stevcev** [comment]
sure! :)

**Comment by felixSchl** [comment]
can we keep using the `PROCESS` row label though? That was my initial motivation for submitting #23.

**Comment by owickstrom** [comment]
@felixSchl Yeah, sure!
