### ISSUE TITLE
Switch to purescript-ansi?

### ISSUE THREAD

**Issue by joneshf** [owickstrom/purescript-spec#59]
I noticed there's some FFI modules for doing ansi color stuff. There's a pure PS implementation that only depends on `purescript-strings`: https://pursuit.purescript.org/packages/purescript-ansi/4.0.0.

Are you up for a PR to use `purescript-ansi` instead of writing FFI modules in this library?

**Comment by owickstrom** [comment]
Yeah, sounds good!

**Comment by joneshf** [comment]
Fixed in d2a2b8b80ca0e24fa3d62fc8cde08e83889559b8
